services:
  # Backend API Configuration
  - type: web
    name: nextsms-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm rebuild bcryptjs
    startCommand: npm start
    plan: free

    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: BACKEND_URL
        value: https://nextsms-backend.onrender.com


  # Frontend Configuration
  - type: web
    name: nextsms-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false


